server {
    listen 80;
    
    location / {
        # Encaminha para o Supabase Cloud 1
        proxy_pass https://rnininxlmxdmcjooqwkc.supabase.co;
        
        # Configurações obrigatórias para SSL/HTTPS funcionar
        proxy_ssl_server_name on;
        proxy_set_header Host rnininxlmxdmcjooqwkc.supabase.co;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Remove encoding para podermos debugar se necessário
        proxy_set_header Accept-Encoding "";
    }
}
